set_property IOSTANDARD LVCMOS33 [get_ports {poX[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {poX[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {poX[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {poX[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports piCount]
set_property IOSTANDARD LVCMOS33 [get_ports piRst]

set_property PACKAGE_PIN D9 [get_ports piCount]
set_property PACKAGE_PIN C9 [get_ports piRst]
set_property PACKAGE_PIN G6 [get_ports {poX[3]}]
set_property PACKAGE_PIN G3 [get_ports {poX[2]}]
set_property PACKAGE_PIN J3 [get_ports {poX[1]}]
set_property PACKAGE_PIN K1 [get_ports {poX[0]}]

set_property PACKAGE_PIN E3 [get_ports piClk]
set_property PACKAGE_PIN D9 [get_ports piEna]
set_property IOSTANDARD LVCMOS33 [get_ports piClk]
set_property IOSTANDARD LVCMOS33 [get_ports piEna]
create_clock -name clk -period 10 [get_ports piClk]