set_property IOSTANDARD LVCMOS33 [get_ports {piPowerSel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {piPowerSel[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {poDirM1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {poDirM1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {poDirM2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {poDirM2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports piClk]
set_property IOSTANDARD LVCMOS33 [get_ports piDirSel]
set_property IOSTANDARD LVCMOS33 [get_ports piMotorSel]
set_property IOSTANDARD LVCMOS33 [get_ports piRst]
set_property IOSTANDARD LVCMOS33 [get_ports piSet]
set_property IOSTANDARD LVCMOS33 [get_ports poPowerM1]
set_property IOSTANDARD LVCMOS33 [get_ports poPowerM2]
create_clock -period 10.000 -name clk [get_ports piClk]

set_property PACKAGE_PIN E3 [get_ports piClk]
set_property PACKAGE_PIN D9 [get_ports piDirSel]
set_property PACKAGE_PIN C9 [get_ports piMotorSel]
set_property PACKAGE_PIN B9 [get_ports piRst]
set_property PACKAGE_PIN B8 [get_ports piSet]
set_property PACKAGE_PIN A8 [get_ports {piPowerSel[1]}]
set_property PACKAGE_PIN C11 [get_ports {piPowerSel[0]}]
set_property PACKAGE_PIN H5 [get_ports {poDirM1[1]}]
set_property PACKAGE_PIN J5 [get_ports {poDirM1[0]}]
set_property PACKAGE_PIN E1 [get_ports {poDirM2[1]}]
set_property PACKAGE_PIN G4 [get_ports {poDirM2[0]}]
set_property PACKAGE_PIN R15 [get_ports poPowerM1]
set_property PACKAGE_PIN P15 [get_ports poPowerM2]

